"""AgiBot X2-Ultra skateboarding environment configurations.

Mirrors ``config/g1/env_cfgs.py``. The skater env and all MDP terms are
robot-agnostic; this file supplies the X2-specific scene entities, contact
sensors, action scale, transition body lists, steer stance, and reference-pose
paths. Body/site names used by the env (``left/right_ankle_roll_link``,
``left/right_foot_1..4``, ``pelvis``, ``torso_link``) match the X2 MJCF.
"""

from mjlab_husky.asset_zoo.robots.agibot_x2.x2_skater_constants import (
  X2_ACTION_SCALE,
  get_x2_robot_cfg,
)
from mjlab_husky.asset_zoo.robots.skateboard.g1_skater_constants import (
  get_skateboard_cfg,
)
from mjlab_husky.envs import G1SkaterManagerBasedRlEnvCfg
from mjlab.envs.mdp.actions import JointPositionActionCfg
from mjlab.managers.termination_manager import TerminationTermCfg
from mjlab.sensor import ContactMatch, ContactSensorCfg
from mjlab_husky.tasks.skater import mdp
from mjlab_husky.tasks.skater.mdp import SkateUniformVelocityCommandCfg
from mjlab_husky.tasks.skater.skater_env_cfg import make_g1_skater_env_cfg


def agibot_x2_skater_env_cfg(play: bool = False) -> G1SkaterManagerBasedRlEnvCfg:
  cfg = make_g1_skater_env_cfg()
  # X2 has more collision geoms than the G1 (12 foot capsules per foot); give the
  # contact/constraint buffers extra headroom.
  cfg.sim.njmax = 500
  cfg.sim.mujoco.ccd_iterations = 50
  cfg.sim.contact_sensor_maxmatch = 64
  cfg.sim.nconmax = 100

  cfg.scene.entities = {"robot": get_x2_robot_cfg(), "skateboard": get_skateboard_cfg()}

  #########################################################
  ##### terrain #####
  #########################################################
  assert cfg.scene.terrain is not None
  cfg.scene.terrain.terrain_type = "plane"
  cfg.scene.terrain.terrain_generator = None

  #########################################################
  ##### reference poses (X2-specific, regenerated by scripts/gen_ref_pose.py) #####
  #########################################################
  cfg.push_ref_pose_path = "dataset/ref_pose/x2_push_start_pose_b.npy"
  cfg.steer_ref_pose_path = "dataset/ref_pose/x2_steer_start_pose_b.npy"

  #########################################################
  ##### contact sensors #####
  #########################################################
  left_feet_ground_cfg = ContactSensorCfg(
    name="left_feet_ground_contact",
    primary=ContactMatch(
      mode="subtree",
      pattern=r"^(left_ankle_roll_link)$",
      entity="robot",
    ),
    secondary=ContactMatch(mode="body", pattern="terrain"),
    fields=("found", "force"),
    reduce="netforce",
    num_slots=1,
    track_air_time=True,
  )

  right_feet_ground_cfg = ContactSensorCfg(
    name="right_feet_ground_contact",
    primary=ContactMatch(
      mode="subtree",
      pattern=r"^(right_ankle_roll_link)$",
      entity="robot",
    ),
    secondary=ContactMatch(mode="body", pattern="terrain"),
    fields=("found", "force"),
    reduce="netforce",
    num_slots=1,
    track_air_time=True,
  )

  left_feet_board_cfg = ContactSensorCfg(
    name="left_feet_board_contact",
    primary=ContactMatch(
      mode="subtree",
      pattern=r"^(left_ankle_roll_link)$",
      entity="robot",
    ),
    secondary=ContactMatch(mode="geom", pattern="skateboard_marker_collision", entity="skateboard"),
    fields=("found", "force"),
    reduce="netforce",
    num_slots=1,
    track_air_time=True,
  )

  right_feet_board_cfg = ContactSensorCfg(
    name="right_feet_board_contact",
    primary=ContactMatch(
      mode="subtree",
      pattern=r"^(right_ankle_roll_link)$",
      entity="robot",
    ),
    secondary=ContactMatch(mode="geom", pattern="skateboard_deck_collision", entity="skateboard"),
    fields=("found", "force"),
    reduce="netforce",
    num_slots=1,
    track_air_time=True,
  )

  robot_collision_cfg = ContactSensorCfg(
    name="robot_collision",
    primary=ContactMatch(mode="subtree", pattern="pelvis", entity="robot"),
    secondary=ContactMatch(mode="subtree", pattern="pelvis", entity="robot"),
    fields=("found",),
    reduce="none",
    num_slots=1,
  )

  skateboard_collision_cfg = ContactSensorCfg(
    name="skateboard_collision",
    primary=ContactMatch(mode="geom", pattern=r".*_wheel_collision$", entity="skateboard"),
    secondary=ContactMatch(mode="body", pattern="terrain"),
    fields=("found", "force"),
    reduce="none",
    num_slots=1,
  )

  # Upper-body / pelvis / head contacts that should never legally happen while
  # skating (X2 collision-geom names; cf. the G1 shin/shoulder/elbow/wrist set).
  illegal_contact_cfg = ContactSensorCfg(
    name="illegal_contact",
    primary=ContactMatch(
      mode="geom",
      pattern=r".*_shoulder_yaw_link_collision|.*_elbow_link_collision|.*_wrist_pitch_link_collision|.*_wrist_roll_link_collision|pelvis_collision|head_pitch_link_collision$",
      entity="robot",
    ),
    fields=("found",),
    reduce="none",
    num_slots=1,
  )

  cfg.scene.sensors = (
    robot_collision_cfg,
    skateboard_collision_cfg,
    left_feet_ground_cfg,
    right_feet_ground_cfg,
    left_feet_board_cfg,
    right_feet_board_cfg,
    illegal_contact_cfg,
  )

  joint_pos_action = cfg.actions["joint_pos"]
  assert isinstance(joint_pos_action, JointPositionActionCfg)
  joint_pos_action.scale = X2_ACTION_SCALE

  cfg.viewer.body_name = "torso_link"

  skate_cmd = cfg.commands["skate"]
  assert isinstance(skate_cmd, SkateUniformVelocityCommandCfg)
  skate_cmd.viz.z_offset = 1.15

  # Transition-tracked bodies. These link names are identical between the G1 and
  # X2 MJCFs, so the same list applies.
  cfg.beizer_names = [
    "pelvis",
    "left_hip_roll_link",
    "left_knee_link",
    "left_ankle_roll_link",
    "right_hip_roll_link",
    "right_knee_link",
    "right_ankle_roll_link",
    "torso_link",
    "left_shoulder_roll_link",
    "left_elbow_link",
    "left_wrist_yaw_link",
    "right_shoulder_roll_link",
    "right_elbow_link",
    "right_wrist_yaw_link",
  ]
  cfg.slerp_names = cfg.beizer_names
  cfg.phase_ratios = [0.0, 0.4, 0.5, 0.95, 1.0]

  # Steer stance target, in X2 joint order (31 dof): left leg(6), right leg(6),
  # waist(3: yaw,pitch,roll), left arm(7), right arm(7), head(2). This is the G1
  # steer stance retargeted onto the X2 (name remap + leg IK) and is kept in sync
  # with dataset/ref_pose/x2_steer_start_pose_b.npy by scripts/gen_ref_pose.py.
  cfg.steer_init_pos = [
    -0.546, 0.21, 0.282, 0.825, -0.422, -0.025,   # left leg
    -0.588, 0.033, 0.117, 0.621, -0.191, 0.067,   # right leg
    -0.01, 0.077, 0.109,                          # waist (yaw, pitch, roll)
    0.0, 0.55, -0.25, -0.55, 0.0, 0.0, 0.0,       # left arm
    0.0, -0.55, -0.25, -0.55, 0.0, 0.0, 0.0,      # right arm
    0.0, 0.0,                                    # head (yaw, pitch)
  ]

  # X2 foot has 12 collision capsules per foot (G1: 7); widen the friction-event
  # geom pattern to match.
  foot_friction = cfg.events["foot_friction"]
  foot_friction.params["asset_cfg"].geom_names = r"^(left|right)_foot([1-9]|1[0-2])_collision$"

  # Apply play mode overrides.
  if play:
    # Effectively infinite episode length.
    cfg.episode_length_s = int(60.0)
    cfg.eval_mode = True
    cfg.observations["policy"].enable_corruption = False
    cfg.terminations = {
      "time_out": TerminationTermCfg(func=mdp.time_out, time_out=True),
    }
    cfg.events.pop("push_robot", None)
  return cfg
